### PR TITLE
add pysptools/doc/source to package data

### LINKED ISSUE #7: Cannot install pysptools in user library
Both
`python -m easy_install --user pysptools`
and
`pip install --user pysptools`
return
`error: Setup script exited with error: can't copy 'pysptools/doc/source': doesn't exist or not a regular file`

### PR DESCRIPTION
**Pull request by ninsbl**
This should fix #7

### CODE REVIEW

**Comment by ctherien** [comment]
The github site is not up to date. A few versions and many fix behind. I
think the best is to remove it.

2018-02-02 5:26 GMT-05:00 Stefan Blumentrath <notifications@github.com>:

**Comment by ninsbl** [comment]
Ah, OK. Thanks for the swift reply.
Would you prefer tickets on sourceforge (I have little experience with the latter)?
I mean the issue still applies for the current version...

**Comment by ctherien** [comment]
Yes the issue still applies. This is the first time that I have a patch
contribution (a few years ago I had help for the documentation, that
explain the gitub, but otherwise there is no activities). Well I don't know
what to do.

2018-02-05 2:06 GMT-05:00 Stefan Blumentrath <notifications@github.com>:

**Comment by ninsbl** [comment]
Hi again, unfortunately, I cannot promise to contribute regularly as my activities are project bound...
And I am no python developer, but a more than average interested user...
But, in general, github (or any git) would be much more appealing to me (and I think also other potential contributors) as contributing is more straight forward...
Currently I am finishing off a GRASS GIS pysptools bridge, that provides pysptools functionality as an addon to GRASS... I let you know as soon as it is published...

**Comment by ctherien** [comment]
Hi Stephan, I understand, github stay the best place for coding
collaboration. I will give a look the next days and keep you in touch.

The GRASS project is very interesting! Let me know.

2018-02-06 4:39 GMT-05:00 Stefan Blumentrath <notifications@github.com>:

**Comment by ninsbl** [comment]
The GRASS addon just got published:
https://svn.osgeo.org/grass/grass-addons/grass7/imagery/i.pysptools.unmix/

Manual pages should be online tomorrow! I got already some feedback about the implementation, so there might be some changes coming. But in general it works nicely and complementary to existing imagery tools...

**Comment by ctherien** [comment]
Great, I will announce it on the documentation's website in a few days. The
site has good traffic.

2018-02-08 8:16 GMT-05:00 Stefan Blumentrath <notifications@github.com>:

**Comment by ctherien** [comment]
The github is up to date. You can push.

2018-02-08 14:33 GMT-05:00 Christian Thérien <christian.therien@gmail.com>:

**Pull request closed without merging**
