### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by chsasank**
Added better documentation

### CODE REVIEW

**Comment by ctherien** [comment]
Documentation reorganization

**Comment by ctherien** [comment]
Hi Sasank,

Version 0.13.5 is uploaded on pypi. I propose to keep the doc on
sourceforge and on some other site as you wish. Downloads are not more than
marginal on sourceforge, but the doc web site is well visited with half
from returning visitors.

Have a good day

2016-03-21 15:42 GMT-04:00 Sasank Chilamkurthy notifications@github.com:

**Comment by chsasank** [comment]
May be Let's host the docs on may be pythonhosted and let's redirect  to
there from sourcefourge?

**Comment by ctherien** [comment]
I can add a link to pythonhosted from the sourceforge doc site somewhere at
the beginning of the index.txt file. It's important that I have an admin
access for doing quick fix or something else. And we have to decide to
install google analytic. It give a good idea of what part of the software
to put the development and documentation effort.

2016-03-27 0:16 GMT-04:00 Sasank Chilamkurthy notifications@github.com:

> May be Let's host the docs on may be pythonhosted and let's redirect to
> there from sourcefourge?
>

**Pull request merged**
